run:
  concurrency: 3
  timeout: 15m
  issues-exit-code: 1
  tests: true

  skip-dirs:
    - design
    - \.gopath

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: code-climate

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  uniq-by-line: false


# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: false

    check-blank: true


    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    # exclude: /path/to/file.txt
  govet:
    # report about shadowed variables
    check-shadowing: false

  golint:
    min-confidence: 0.8

  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 18
  maligned:
    suggest-new: true
  dupl:
    threshold: 175
  goconst:
    min-len: 3
    min-occurrences: 3
  funlen:
    lines: 80
    statements: 50
  godox:
    keywords:
      - HACK
      - OPTIMIZE
      - TODO
      - BUG
  misspell:
    locale: UK
    ignore-words:
  lll:
    line-length: 120
    tab-width: 2
  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 0
  prealloc:
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default

  gocritic:
    enabled-checks:

    disabled-checks:
      - regexpMust

    enabled-tags:
      - performance

    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - lll
    - goimports # incompatible with gofmt
    - depguard
    - wsl
    - dogsled
    - unused # Results in panic: https://github.com/golangci/golangci-lint/issues/979
    - godot
    - testpackage
  disable-all: false
  fast: false


issues:
  exclude-rules:

    # For projects that use cobra we allow globals and inits
    - linters:
        - gochecknoglobals
        - gochecknoinits
      path: cmd/

    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint
        - gocritic
        - funlen

    - linters:
        - staticcheck
      text: "SA9003:"


    - linters:
        - lll
      text: "^//go:generate "

  exclude-use-default: false

  max-issues-per-linter: 0

  max-same-issues: 0

  new: false

